epochs: 500
batch_size: 32
lr: 1e-4
weight_decay: 0
early_stop_patience: 100
data:
  train_data: './data/x_train.npy'
  train_labels: './data/y_train.npy'
  dev_data: './data/x_dev.npy'
  dev_labels: './data/y_dev.npy'
  test_data: './data/x_test.npy'
  test_labels: './data/y_test.npy'
model:
  n_layers: 1
  n_hidden: 20
  n_classes: 6
  dropout: 0

defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
hydra:
  job:
    chdir: true
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 420
    direction: maximize
    study_name: Text_Classification 
    storage: null
    n_trials: 30
    n_jobs: 1
    max_failure_rate: 0.0
    params:
      batch_size: choice(2, 4, 8, 16, 32, 64, 128)
      lr: tag(log, interval(0.00001, 0.1))
      model.n_layers: range(1, 10, step=1)
      model.n_hidden: range(1, 10, step=1)
      model.dropout: range(0, 0.3, step=0.01)

# if true, simulate a failure by raising an exception
error: false
